[book]
title = "OERV VIRT"
description = "openEuler RISC-V Virtualization Team"
authors = ["Ruoqing He"]
language = "en"
multilingual = false
src = "src"

[rust]
edition = "2021"

[output.html]
smart-punctuation = true
mathjax-support = true
#site-url = "/mdBook/"
#git-repository-url = "https://github.com/rust-lang/mdBook/tree/master/guide"
#edit-url-template = "https://github.com/rust-lang/mdBook/edit/master/guide/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.code.hidelines]
python = "~"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
